---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - ansible.builtin.dnf:
      name:
      - requests
      - docker
      state: present

  - community.docker.docker_image:
      name: almalinux/8-base
      source: pull
